/**
 * Executes inside of electron's main process.
 */
import { app } from "electron";
import { DesktopToolsWindow } from "./app/window";
import path from "path";
import fs from "fs";

/**
 * This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
 * plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
 * whether you're running in development or production).
 */
export declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
export declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require("electron-squirrel-startup")) app.quit();

app.setAppUserModelId("com.squirrel.DesktopToolbox.DesktopToolbox");

async function createApplicationWindow() {
  const localSharpPath = path.join(
    process.resourcesPath,
    "app.asar.unpacked",
    "node_modules",
    "sharp"
  );

  // Only do this if it looks like the real package is missing
  if (!fs.existsSync(path.join(__dirname, "node_modules/sharp"))) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require("module").globalPaths.push(localSharpPath);
    console.log(`Adding \`sharp\` from '${localSharpPath}' to global paths.`);
  }

  const window = new DesktopToolsWindow({
    windowEvents: {
      onReady: (window) => {
        window.show();
      },
      onClose: () => {
        app.quit();
      }
    },
    icon: path.join(app.getAppPath(), "assets", "icon.png")
  });
  return window;
}

app.on("ready", async () => {
  const appWindow = await createApplicationWindow();
  await appWindow.init();
});
