import electron, { Menu, BrowserWindow } from "electron";
import installDevToolExtension, {
  REDUX_DEVTOOLS,
  REACT_DEVELOPER_TOOLS
} from "electron-devtools-installer";
import { imageToIconEventHandler } from "./app/ipc/image-to-icon/event-handlers";
import { inDebugMode } from "./utils";
import packageJson from "../../package.json";

/**
 * This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
 * plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
 * whether you're running in development or production).
 */
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

type DesktopToolsWindowConfig = {
  windowEvents: {
    onReady: (window: BrowserWindow) => void;
    onClose: (window: BrowserWindow) => void;
  };
  icon?: string;
};

export class DesktopToolsWindow {
  private window: BrowserWindow;

  constructor({ windowEvents, icon }: DesktopToolsWindowConfig) {
    this.window = new BrowserWindow({
      title: packageJson.displayName,
      icon,
      width: 1200,
      height: 1600,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        nodeIntegration: true
      },
      resizable: true
    });

    this.window.on("ready-to-show", () => {
      windowEvents.onReady(this.window);
    });

    this.window.on("close", () => {
      windowEvents.onClose(this.window);
    });

    this.attachToMainProcess(imageToIconEventHandler);
  }

  private addWindowMenu() {
    const menu = Menu.buildFromTemplate([
      {
        label: "File",
        submenu: [
          {
            label: "Exit",
            role: "quit"
          },
          { label: "Reload", role: "reload", accelerator: "Ctrl+R" },
          {
            label: "DevTools",
            role: "toggleDevTools",
            accelerator: "Ctrl+`"
          }
        ]
      }
    ]);

    this.window.webContents.on("context-menu", (_, props) => {
      const { x, y } = props;

      Menu.buildFromTemplate([
        {
          label: "Inspect element",
          click: () => {
            this.window.webContents.inspectElement(x, y);
          }
        }
      ]).popup({ window: this.window });
    });

    Menu.setApplicationMenu(menu);
  }

  public onClose(callback: () => void) {
    this.window.on("close", (event) => {
      event.preventDefault();
      callback();
    });
  }

  private attachToMainProcess(attachHandler: (ipcMain: Electron.IpcMain) => void) {
    attachHandler(electron.ipcMain);
  }

  public async installDevToolExtensions() {
    const supportedExtensions = {
      [REACT_DEVELOPER_TOOLS.id]: {
        name: "react-devtools",
        reference: REACT_DEVELOPER_TOOLS
      },
      [REDUX_DEVTOOLS.id]: {
        name: "redux-devtools",
        reference: REDUX_DEVTOOLS
      }
    };

    for (const supportedExtension of Object.entries(supportedExtensions)) {
      const extensionId = supportedExtension[0];
      const extensionDetails = supportedExtension[1];

      try {
        await installDevToolExtension(extensionDetails.reference, {
          forceDownload: true,
          session: this.window.webContents.session,
          loadExtensionOptions: {
            allowFileAccess: true
          }
        });

        console.log(`Installed DevTools extension: ${extensionDetails.name} (${extensionId})`);
      } catch (error) {
        throw new Error(
          [
            `Failed to install devtools extension: ${extensionDetails.name}`,
            `Message: ${error.message}`,
            `Details: ${error.stack}`
          ].join("\n")
        );
      }
    }

    return this;
  }

  public async init() {
    await this.installDevToolExtensions();

    await this.window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    if (inDebugMode()) {
      this.addWindowMenu();
      this.window.webContents.openDevTools({ mode: "right" });
    }
  }
}
