// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/image-to-icon-converter": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/image-to-icon-converter";
  };
  "./error-boundary.tsx": {
    id: "error-boundary";
    page: "/*";
  };
  "./routes/dashboard/dashboard.tsx": {
    id: "routes/dashboard/dashboard";
    page: "/";
  };
  "./routes/tools/image-to-icon-converter/image-to-icon-converter.tsx": {
    id: "routes/tools/image-to-icon-converter/image-to-icon-converter";
    page: "/image-to-icon-converter";
  };
};